server: 
  port: 9002
spring: 
  application:  
    name: renwen-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/renwen_article?characterEncoding=UTF8
    username: root
    password: w1257096364
  jpa: 
    database: MySQL
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka #,http://eureka7002.com:7002/eureka/,
      #http://eureka7002.com:7002/eureka/
      #将服务注册进eureka集群
  instance:
    instance-id: renwen-article
    prefer-ip-address: true #显示IP地址
