server: 
  port: 9004
spring: 
  application:  
    name: renwen-spit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/renwen_spit?characterEncoding=UTF8
    username: root
    password: w1257096364
  jpa: 
    database: MySQL
    show-sql: true
  jackson:
        date-format: yyyy-MM-dd HH:mm:ss